package storage

const schema = `
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS schema_migrations (
	version INTEGER PRIMARY KEY,
	applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS steam_libraries (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	path TEXT NOT NULL UNIQUE,
	created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS games (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	steam_app_id TEXT NOT NULL UNIQUE,
	name TEXT NOT NULL,
	install_dir TEXT NOT NULL,
	library_path TEXT NOT NULL,
	game_path TEXT NOT NULL,
	state TEXT NOT NULL DEFAULT 'clean_candidate',
	created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS game_markers (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	game_id INTEGER NOT NULL REFERENCES games(id) ON DELETE CASCADE,
	path TEXT NOT NULL,
	kind TEXT NOT NULL,
	UNIQUE(game_id, path)
);

CREATE TABLE IF NOT EXISTS profiles (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	game_id INTEGER NOT NULL REFERENCES games(id) ON DELETE CASCADE,
	name TEXT NOT NULL,
	is_default INTEGER NOT NULL DEFAULT 0,
	created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(game_id, name)
);

CREATE TABLE IF NOT EXISTS catalog_accounts (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	catalog TEXT NOT NULL UNIQUE,
	api_key TEXT NOT NULL DEFAULT '',
	created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mods (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	game_id INTEGER NOT NULL REFERENCES games(id) ON DELETE CASCADE,
	catalog TEXT NOT NULL,
	source_url TEXT NOT NULL,
	source_game_domain TEXT NOT NULL DEFAULT '',
	source_mod_id TEXT NOT NULL DEFAULT '',
	name TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(game_id, catalog, source_mod_id)
);

CREATE TABLE IF NOT EXISTS mod_versions (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	mod_id INTEGER NOT NULL REFERENCES mods(id) ON DELETE CASCADE,
	version TEXT NOT NULL,
	source_file_id TEXT NOT NULL DEFAULT '',
	metadata_json TEXT NOT NULL DEFAULT '{}',
	created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(mod_id, version, source_file_id)
);

CREATE TABLE IF NOT EXISTS downloads (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	mod_version_id INTEGER REFERENCES mod_versions(id) ON DELETE SET NULL,
	source_url TEXT NOT NULL,
	archive_path TEXT NOT NULL DEFAULT '',
	checksum_sha256 TEXT NOT NULL DEFAULT '',
	status TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS installed_mods (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	mod_version_id INTEGER NOT NULL REFERENCES mod_versions(id) ON DELETE CASCADE,
	staging_path TEXT NOT NULL,
	checksum_manifest_json TEXT NOT NULL DEFAULT '{}',
	created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(mod_version_id)
);

CREATE TABLE IF NOT EXISTS profile_mods (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	profile_id INTEGER NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
	installed_mod_id INTEGER NOT NULL REFERENCES installed_mods(id) ON DELETE CASCADE,
	enabled INTEGER NOT NULL DEFAULT 1,
	priority INTEGER NOT NULL DEFAULT 0,
	created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(profile_id, installed_mod_id)
);

CREATE TABLE IF NOT EXISTS deployments (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	game_id INTEGER NOT NULL REFERENCES games(id) ON DELETE CASCADE,
	profile_id INTEGER NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
	status TEXT NOT NULL,
	strategy TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS deployed_files (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	deployment_id INTEGER NOT NULL REFERENCES deployments(id) ON DELETE CASCADE,
	source_path TEXT NOT NULL,
	target_path TEXT NOT NULL,
	link_type TEXT NOT NULL,
	checksum_sha256 TEXT NOT NULL DEFAULT '',
	created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(deployment_id, target_path)
);

CREATE TABLE IF NOT EXISTS file_conflicts (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	profile_id INTEGER NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
	target_path TEXT NOT NULL,
	winner_installed_mod_id INTEGER REFERENCES installed_mods(id) ON DELETE SET NULL,
	conflict_json TEXT NOT NULL DEFAULT '{}',
	created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(profile_id, target_path)
);

CREATE TABLE IF NOT EXISTS jobs (
	id TEXT PRIMARY KEY,
	type TEXT NOT NULL,
	title TEXT NOT NULL,
	status TEXT NOT NULL,
	message TEXT NOT NULL DEFAULT '',
	payload_json TEXT NOT NULL DEFAULT '{}',
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);
`
