package extensions

import (
	"github.com/justyntemme/decky-mod-manager/internal/extensions/ahatintime"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/bastion"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/besiege"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/blasphemous"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/braid"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/brawlhalla"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/citizensleeper"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/civilizationvii"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/commandconquergenerals"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/commandconquergeneralszerohour"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/commoninterpreters"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/cultistsimulator"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/daggerfallunity"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/davethediver"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/dirtrally"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/discoelysium"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/dwarffortress"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/elex"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/fallout4"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/fez"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/finalfantasy7rebirth"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/finalfantasyxx2hdremaster"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/galacticcivilizations3"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/gamebryoarchive"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/gamestores"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/gameversionhash"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/ghostreconbreakpoint"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/gnorpapologue"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/godhood"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/greedfall"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/halflife"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/halflife2"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/halflife2episodes"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/heavybullets"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/hollowknight"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/hotlinemiami"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/kenshi"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/markoftheninja"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/masterchiefcollection"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/mcpixel"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/megabonk"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/metalgearandmetalgear2mc"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/metalgearsolid2mc"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/metalgearsolid3mc"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/metalgearsolidmc"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/metalgearsolidvtpp"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/metroexodus"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/mewgenics"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/mirrorsedge"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/mrprepper"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/mtframeworkarc"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/nuclearoption"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/nuclearthrone"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/persona5royal"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/plagueincevolved"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/planetside2"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/portal2"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/potioncraft"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/projectzomboid"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/prototype"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/prototype2"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/quake4"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/quickbmssupport"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/ridersrepublic"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/rimworld"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/rometotalwar"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/sekiro"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/sharedmodtypes"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/shieldwall"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/skyrimse"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/sleepingdogs"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/sno"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/spelunky"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/spidermanmilesmorales"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/spyroreignitedtrilogy"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/stacklands"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/stardewvalley"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/starwarsbattlefrontii"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/starwarsjedisurvivor"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/starwarsroguesquadron"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/steinsgate"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/stellaris"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/survivingmars"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/tabletopsimulator"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/thebindingofisaacrebirth"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/thedivision2"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/thekingiswatching"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/thomaswasalone"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/torchlight2"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/totalwarpharaohdynasties"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/totalwarrome2"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/totalwarromeremastered"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/transportfever2"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/vortexgamecatalog"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/vortexsharedsystems"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/vortexuisurfaces"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/warno"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/wewhoareabouttodie"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/witcher3"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/x4foundations"
	"github.com/justyntemme/decky-mod-manager/internal/extensions/xrebirth"
	"github.com/justyntemme/decky-mod-manager/internal/gameext"
)

func FirstParty() []gameext.Extension {
	extensions := []gameext.Extension{
		gameext.MustCompileExtension(commoninterpreters.Extension()),
		gameext.MustCompileExtension(gamebryoarchive.Extension()),
		gameext.MustCompileExtension(gamestores.Extension()),
		gameext.MustCompileExtension(gameversionhash.Extension()),
		gameext.MustCompileExtension(mtframeworkarc.Extension()),
		gameext.MustCompileExtension(quickbmssupport.Extension()),
		gameext.MustCompileExtension(sharedmodtypes.Extension()),
		gameext.MustCompileExtension(vortexsharedsystems.Extension()),
		gameext.MustCompileExtension(vortexuisurfaces.Extension()),
	}
	for _, extension := range vortexgamecatalog.Extensions() {
		extensions = append(extensions, gameext.MustCompileExtension(extension))
	}
	extensions = append(extensions,
		gameext.MustCompileExtension(ahatintime.Extension()),
		gameext.MustCompileExtension(bastion.Extension()),
		gameext.MustCompileExtension(besiege.Extension()),
		gameext.MustCompileExtension(blasphemous.Extension()),
		gameext.MustCompileExtension(braid.Extension()),
		gameext.MustCompileExtension(brawlhalla.Extension()),
		gameext.MustCompileExtension(civilizationvii.Extension()),
		gameext.MustCompileExtension(citizensleeper.Extension()),
		gameext.MustCompileExtension(commandconquergenerals.Extension()),
		gameext.MustCompileExtension(commandconquergeneralszerohour.Extension()),
		gameext.MustCompileExtension(cultistsimulator.Extension()),
		gameext.MustCompileExtension(daggerfallunity.Extension()),
		gameext.MustCompileExtension(davethediver.Extension()),
		gameext.MustCompileExtension(discoelysium.Extension()),
		gameext.MustCompileExtension(dirtrally.Extension()),
		gameext.MustCompileExtension(dwarffortress.Extension()),
		gameext.MustCompileExtension(elex.Extension()),
		gameext.MustCompileExtension(finalfantasy7rebirth.Extension()),
		gameext.MustCompileExtension(fallout4.Extension()),
		gameext.MustCompileExtension(fez.Extension()),
		gameext.MustCompileExtension(ghostreconbreakpoint.Extension()),
		gameext.MustCompileExtension(galacticcivilizations3.Extension()),
		gameext.MustCompileExtension(gnorpapologue.Extension()),
		gameext.MustCompileExtension(godhood.Extension()),
		gameext.MustCompileExtension(greedfall.Extension()),
		gameext.MustCompileExtension(halflife.Extension()),
		gameext.MustCompileExtension(halflife2.Extension()),
		gameext.MustCompileExtension(halflife2episodes.Extensions()[0]),
		gameext.MustCompileExtension(halflife2episodes.Extensions()[1]),
		gameext.MustCompileExtension(halflife2episodes.Extensions()[2]),
		gameext.MustCompileExtension(heavybullets.Extension()),
		gameext.MustCompileExtension(hollowknight.Extension()),
		gameext.MustCompileExtension(hotlinemiami.Extension()),
		gameext.MustCompileExtension(kenshi.Extension()),
		gameext.MustCompileExtension(markoftheninja.Extension()),
		gameext.MustCompileExtension(finalfantasyxx2hdremaster.Extension()),
		gameext.MustCompileExtension(masterchiefcollection.Extension()),
		gameext.MustCompileExtension(mcpixel.Extension()),
		gameext.MustCompileExtension(megabonk.Extension()),
		gameext.MustCompileExtension(metalgearandmetalgear2mc.Extension()),
		gameext.MustCompileExtension(metalgearsolidvtpp.Extension()),
		gameext.MustCompileExtension(metalgearsolidmc.Extension()),
		gameext.MustCompileExtension(metalgearsolid2mc.Extension()),
		gameext.MustCompileExtension(metalgearsolid3mc.Extension()),
		gameext.MustCompileExtension(metroexodus.Extension()),
		gameext.MustCompileExtension(mewgenics.Extension()),
		gameext.MustCompileExtension(mirrorsedge.Extension()),
		gameext.MustCompileExtension(mrprepper.Extension()),
		gameext.MustCompileExtension(nuclearoption.Extension()),
		gameext.MustCompileExtension(nuclearthrone.Extension()),
		gameext.MustCompileExtension(persona5royal.Extension()),
		gameext.MustCompileExtension(portal2.Extension()),
		gameext.MustCompileExtension(plagueincevolved.Extension()),
		gameext.MustCompileExtension(planetside2.Extension()),
		gameext.MustCompileExtension(potioncraft.Extension()),
		gameext.MustCompileExtension(prototype.Extension()),
		gameext.MustCompileExtension(prototype2.Extension()),
		gameext.MustCompileExtension(projectzomboid.Extension()),
		gameext.MustCompileExtension(quake4.Extension()),
		gameext.MustCompileExtension(rimworld.Extension()),
		gameext.MustCompileExtension(ridersrepublic.Extension()),
		gameext.MustCompileExtension(rometotalwar.Extension()),
		gameext.MustCompileExtension(sekiro.Extension()),
		gameext.MustCompileExtension(shieldwall.Extension()),
		gameext.MustCompileExtension(sleepingdogs.Extension()),
		gameext.MustCompileExtension(skyrimse.Extension()),
		gameext.MustCompileExtension(sno.Extension()),
		gameext.MustCompileExtension(stardewvalley.Extension()),
		gameext.MustCompileExtension(spidermanmilesmorales.Extension()),
		gameext.MustCompileExtension(spelunky.Extension()),
		gameext.MustCompileExtension(starwarsbattlefrontii.Extension()),
		gameext.MustCompileExtension(starwarsroguesquadron.Extension()),
		gameext.MustCompileExtension(starwarsjedisurvivor.Extension()),
		gameext.MustCompileExtension(steinsgate.Extension()),
		gameext.MustCompileExtension(stellaris.Extension()),
		gameext.MustCompileExtension(stacklands.Extension()),
		gameext.MustCompileExtension(survivingmars.Extension()),
		gameext.MustCompileExtension(tabletopsimulator.Extension()),
		gameext.MustCompileExtension(thebindingofisaacrebirth.Extension()),
		gameext.MustCompileExtension(thedivision2.Extension()),
		gameext.MustCompileExtension(thekingiswatching.Extension()),
		gameext.MustCompileExtension(thomaswasalone.Extension()),
		gameext.MustCompileExtension(torchlight2.Extension()),
		gameext.MustCompileExtension(spyroreignitedtrilogy.Extension()),
		gameext.MustCompileExtension(totalwarpharaohdynasties.Extension()),
		gameext.MustCompileExtension(totalwarrome2.Extension()),
		gameext.MustCompileExtension(totalwarromeremastered.Extension()),
		gameext.MustCompileExtension(transportfever2.Extension()),
		gameext.MustCompileExtension(warno.Extension()),
		gameext.MustCompileExtension(wewhoareabouttodie.Extension()),
		gameext.MustCompileExtension(witcher3.Extension()),
		gameext.MustCompileExtension(x4foundations.Extension()),
		gameext.MustCompileExtension(xrebirth.Extension()),
	)
	return extensions
}
